services:
  nginx:
    image: nginx:latest
    ports:
      - "9696:9696"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # - ./ssl:/etc/nginx/ssl:ro


  app:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    ports:
      - "80:8080"
    expose:
      - "8080"
