volumes:
  shared-storage:

services:
  web:
    image: nginx:https-for-stirling
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl/server.crt:/nginx/server.crt
      - ./ssl/server.key:/nginx/server.key

  app:
    image: stirlingpdf:https-for-stirling
    build:
      context: .
      dockerfile: stirlingpdf.dockerfile
    volumes:
      - shared-storage:/usr/share/tessdata:ro

  anubis:
    image: anubis:anubis-for-smth
    build:
      context: .
      dockerfile: anubis.dockerfile

  tesseract:
    image: tesseract:tesseract-for-stirling
    build:
      context: .
      dockerfile: tesseract.dockerfile
    volumes:
      - shared-storage:/usr/share/tessdata
