server {
  listen 443 ssl;  
  listen [::]:443 ssl;  
  server_name localhost;
  ssl_certificate     /nginx/server.crt;
  ssl_certificate_key /nginx/server.key;
  ssl_protocols       TLSv1.2 TLSv1.3;
  client_max_body_size 0;
  http2 on;

  location / {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Http-Version $server_protocol;
    proxy_pass http://anubis:8923/;
  }
}
  
server {
  listen 80;  
  listen [::]:80;  
  server_name localhost;
  client_max_body_size 0;
  http2 on;

  return 301 https://$server_name$request_uri;
}
