server {
  listen 443 ssl;  
  server_name localhost;
  ssl_certificate     /nginx/server.crt;
  ssl_certificate_key /nginx/server.key;
  ssl_protocols       TLSv1.2 TLSv1.3;

  location / {
    proxy_pass http://app:8080;
  }
}
  